#What type of bells are there in this church/bell tower?

SELECT ?b ?bDesc 
WHERE {
	?b a-cd:isLocatedIn<https://w3id.org/arco/resource/ArchitecturalOrLandscapeHeritage/0700109690> ;
	dc:description ?bDesc ;
	dc:subject ?o FILTER(str(?o)='campana')
}

