#12. What documentation we have on the “a tastiera” bell technique?

SELECT ?t ?a ?docURL
WHERE {
	?t rdf:type arco:DemoEthnoAnthropologicalHeritage ;
	a-loc:hasCulturalPropertyAddress ?l ;
	dc:subject ?o FILTER regex(str(?o), "tastiera") .
	?l rdfs:label ?a .
	?doc a-cd:isDocumentationOf ?t ;
	<https://w3id.org/italia/onto/SM/URL> ?docURL .
}


